import {
  workbenchThreeFrameIntervalForCells,
  type WorkbenchThreeTerminalPressureOptions,
} from "../src/app/workbench_three_terminal_pressure.ts";

export const WORKBENCH_THREE_LIVE_MAX_CELLS = 960;
export const WORKBENCH_THREE_RESCUE_CELLS = 30;
export const WORKBENCH_THREE_EMERGENCY_CELLS = 60;
export const WORKBENCH_THREE_INITIAL_CELLS = 120;

export const WORKBENCH_THREE_PRESSURE_LEVELS = [
  WORKBENCH_THREE_RESCUE_CELLS,
  WORKBENCH_THREE_EMERGENCY_CELLS,
  120,
  240,
  480,
  WORKBENCH_THREE_LIVE_MAX_CELLS,
] as const;

export const WORKBENCH_THREE_PRESSURE_HIGH_BYTES = 240_000;
export const WORKBENCH_THREE_PRESSURE_LOW_BYTES = 35_000;
export const WORKBENCH_THREE_PRESSURE_HIGH_BYTES_PER_GRID = 160_000;
export const WORKBENCH_THREE_PRESSURE_LOW_BYTES_PER_GRID = 12_000;
export const WORKBENCH_THREE_PRESSURE_HIGH_BYTES_PER_SECOND = 180_000;
export const WORKBENCH_THREE_PRESSURE_LOW_BYTES_PER_SECOND = 20_000;
export const WORKBENCH_THREE_PRESSURE_HIGH_DURATION_MS = 50;
export const WORKBENCH_THREE_PRESSURE_HIGH_FRAME_THRESHOLD = 4;
export const WORKBENCH_THREE_PRESSURE_LOW_FRAME_THRESHOLD = 30;
export const WORKBENCH_THREE_DRAW_INTERVAL_MS = 1000 / 30;
export const WORKBENCH_THREE_RESCUE_DRAW_INTERVAL_MS = 1000 / 15;
export const WORKBENCH_THREE_EMERGENCY_DRAW_INTERVAL_MS = 1000 / 20;
export const WORKBENCH_THREE_READBACK_STRATEGY = "blocking" as const;

export const WORKBENCH_THREE_FRAME_INTERVAL_BY_CELLS = new Map<number, number>([
  [WORKBENCH_THREE_RESCUE_CELLS, WORKBENCH_THREE_RESCUE_DRAW_INTERVAL_MS],
  [WORKBENCH_THREE_EMERGENCY_CELLS, WORKBENCH_THREE_EMERGENCY_DRAW_INTERVAL_MS],
  [120, WORKBENCH_THREE_DRAW_INTERVAL_MS],
  [240, WORKBENCH_THREE_DRAW_INTERVAL_MS],
  [480, 1000 / 24],
  [WORKBENCH_THREE_LIVE_MAX_CELLS, 1000 / 20],
  [1_920, 1000 / 14],
  [3_840, 1000 / 10],
]);

export const WORKBENCH_THREE_IDLE_FRAME_INTERVAL_BY_CELLS = new Map<number, number>([
  [WORKBENCH_THREE_RESCUE_CELLS, 1000 / 8],
  [WORKBENCH_THREE_EMERGENCY_CELLS, 1000 / 8],
  [120, 1000 / 8],
  [240, 1000 / 8],
  [480, 1000 / 8],
  [WORKBENCH_THREE_LIVE_MAX_CELLS, 1000 / 8],
  [1_920, 1000 / 6],
  [3_840, 1000 / 5],
]);

export type ApiWorkbenchThreePressurePolicy = Omit<
  WorkbenchThreeTerminalPressureOptions,
  "renderedThreeGrids" | "bytes" | "durationMs"
>;

export const API_WORKBENCH_THREE_PRESSURE_POLICY: ApiWorkbenchThreePressurePolicy = {
  levels: WORKBENCH_THREE_PRESSURE_LEVELS,
  highBytes: WORKBENCH_THREE_PRESSURE_HIGH_BYTES,
  lowBytes: WORKBENCH_THREE_PRESSURE_LOW_BYTES,
  highBytesPerGrid: WORKBENCH_THREE_PRESSURE_HIGH_BYTES_PER_GRID,
  lowBytesPerGrid: WORKBENCH_THREE_PRESSURE_LOW_BYTES_PER_GRID,
  highBytesPerSecond: WORKBENCH_THREE_PRESSURE_HIGH_BYTES_PER_SECOND,
  lowBytesPerSecond: WORKBENCH_THREE_PRESSURE_LOW_BYTES_PER_SECOND,
  highDurationMs: WORKBENCH_THREE_PRESSURE_HIGH_DURATION_MS,
  highFrameThreshold: WORKBENCH_THREE_PRESSURE_HIGH_FRAME_THRESHOLD,
  lowFrameThreshold: WORKBENCH_THREE_PRESSURE_LOW_FRAME_THRESHOLD,
};

export function apiWorkbenchThreeFrameIntervalForCells(cells: number, options: { live?: boolean } = {}): number {
  return workbenchThreeFrameIntervalForCells(cells, {
    live: options.live,
    liveIntervals: WORKBENCH_THREE_FRAME_INTERVAL_BY_CELLS,
    idleIntervals: WORKBENCH_THREE_IDLE_FRAME_INTERVAL_BY_CELLS,
    liveDefaultMs: WORKBENCH_THREE_DRAW_INTERVAL_MS,
    idleDefaultMs: 1000 / 8,
  });
}
