// Copyright 2023 Im-Beast. MIT license.

/** Serializable report describing the supported HTML/CSS-style TUI authoring subset. */
export interface TuiCssSupportReport {
  layoutDisplays: string[];
  selectors: string[];
  pseudoStates: string[];
  mediaFeatures: string[];
  properties: string[];
  lengthUnits: string[];
  markupTags: string[];
  hydratedWidgetTags: string[];
  unsupported: string[];
}

const supportedProperties = [
  "display",
  "position",
  "flex-direction",
  "flex-wrap",
  "flex-flow",
  "flex-grow",
  "flex-shrink",
  "flex-basis",
  "flex",
  "align-items",
  "justify-content",
  "align-self",
  "justify-self",
  "place-self",
  "grid-template-columns",
  "grid-template-rows",
  "grid-template-areas",
  "grid-auto-columns",
  "grid-auto-rows",
  "grid-auto-flow",
  "grid-column",
  "grid-row",
  "grid-area",
  "grid-column-start",
  "grid-column-end",
  "grid-row-start",
  "grid-row-end",
  "width",
  "height",
  "min-width",
  "min-height",
  "max-width",
  "max-height",
  "inset",
  "top",
  "right",
  "bottom",
  "left",
  "margin",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "padding",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "border",
  "border-width",
  "border-top",
  "border-right",
  "border-bottom",
  "border-left",
  "border-style",
  "border-color",
  "gap",
  "row-gap",
  "column-gap",
  "overflow",
  "overflow-x",
  "overflow-y",
  "z-index",
  "color",
  "background",
  "background-color",
  "visibility",
  "white-space",
  "overflow-wrap",
  "word-wrap",
] as const;

const supportedHydratedWidgetTags = [
  "button",
  "checkbox",
  "combo-box",
  "combobox",
  "div",
  "form",
  "input",
  "menu-bar",
  "panel",
  "radio-group",
  "scroll-area",
  "select",
  "slider",
  "statusbar",
  "tabs",
  "text-box",
  "textarea",
  "textbox",
  "toolbar",
  "tree",
] as const;

/** Returns the stable supported subset and known gaps for the HTML/CSS-style layout engine. */
export function inspectTuiCssSupport(): TuiCssSupportReport {
  return {
    layoutDisplays: ["block", "flex", "grid", "none"],
    selectors: ["tag", ".class", "#id", "*", "child >", "descendant", "selector lists"],
    pseudoStates: ["active", "disabled", "focus", "hover"],
    mediaFeatures: ["min-width", "max-width", "min-height", "max-height"],
    properties: [...supportedProperties],
    lengthUnits: ["cells", "%", "fr", "auto"],
    markupTags: [
      "window",
      "div",
      "panel",
      "toolbar",
      "menu-bar",
      "statusbar",
      "scroll-area",
      "form",
      "button",
      "input",
      "checkbox",
      "radio-group",
      "select",
      "combo-box",
      "combobox",
      "slider",
      "textarea",
      "text-box",
      "textbox",
      "table",
      "tree",
      "tabs",
      "modal",
      "three-ascii",
    ],
    hydratedWidgetTags: [...supportedHydratedWidgetTags],
    unsupported: [
      "browser CSS parser parity",
      "em/rem/vh/vw/calc/container-query units",
      "floats",
      "transforms",
      "animations and transitions",
      "shadows, filters, gradients, and compositing effects",
      "complex pseudo classes and pseudo elements",
      "named grid lines",
      "Yoga solver named grid-area parity",
      "subgrid",
      "dense browser Grid packing parity",
      "full browser intrinsic sizing and baseline alignment",
    ],
  };
}
