// Copyright 2023 Im-Beast. MIT license.

// GENERATED FILE — do not edit by hand.
// Regenerate with: deno run -A scripts/audit_butterchurn_catalog.ts
//
// The presets the butterchurn background cycles through, selected by rendering
// each one and keeping those that resolve to a moving image at terminal
// resolution. Of 293 presets in the catalog: 171 ok, 101 blank, 12 saturated, 9 static.
//
// The excluded ones are not broken — most draw with custom waves, custom shapes
// and a composite shader, none of which this renderer runs, so they resolve to
// an empty screen. Every preset remains selectable by index through
// `EXOMUX_BUTTERCHURN_CATALOG`; this list only decides what auto-cycling walks.

/** Names of the presets worth cycling, in catalog order. */
export const EXOMUX_BUTTERCHURN_ROTATION: readonly string[] = [
  "$$$ Royal - Mashup (220)",
  "$$$ Royal - Mashup (273)",
  "$$$ Royal - Mashup (307)",
  "$$$ Royal - Mashup (431)",
  "$$$ Royal - Mashup (489)",
  "269",
  "_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)",
  "_Flexi, martin + geiss - painterly rogue wave strike (color emboss mix)",
  "_Geiss - Artifact 01",
  "_Geiss - Desert Rose 2",
  "_Geiss - untitled",
  "_geiss_experimental__wavefronts",
  "_Mig_028",
  "_Mig_049",
  "_Mig_079",
  "_Mig_COLORFUL9",
  "_Mig_Oscilloscope008",
  "_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)",
  "AdamFX Mashup 2 Martin - reflections on black tile + Raron N Flexi ",
  "Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix",
  "Aderrasi + Geiss - Airhandler (Kali Mix) - Painterly Tendrils Colorfast",
  "Aderrasi - Airhandler (Last Breath - Calm)",
  "Aderrasi - Mother Of Pearl - mash0000 - how to piss off your eyes",
  "Aderrasi - Potion of Spirits",
  "Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics",
  "Aderrasi - Veil of Steel (Steel Storm) - mash0000 - bob ross finally loses it",
  "An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B",
  "beta106i - Burning Form (Seething Mass) - mash0000 - fire paint easter egg internals",
  "cope + flexi - colorful marble (ghost mix)",
  "cope + geiss + stahlregen - cartune (bending gelatine mix)",
  "cope + martin - mother-of-pearl",
  "Cope - Passage (mandala mix)",
  "cope - strange attractor [flexis let it grow mix] (Jelly 5.56 [volume noise zoom-in])",
  "cope - the drain to heaven",
  "Cope - The Neverending Explosion of Red Liquid Fire",
  "cope, martin + flexi - the slickery of alternative varnish",
  "fed + flexi + geiss - tokamak repellor tech twist mix [stabilized]",
  "fishbrain + flexi - stitchcraft",
  "fiShbRaiN + Flexi - witchcraft 2.0",
  "fiShbRaiN + geiss - witchcraft (Grow Mix 3)",
  "fiShbRaiN - toffee cream and icing sugar",
  "fiShbRaiN, flexi + martin - grafitti tagging witchcraft must be overrated - demonlord shaders - lampshade hubrys2",
  "flexi + fishbrain - neon mindblob grafitti",
  "Flexi + fiShbRaiN - operation fatcap II",
  "flexi + fishbrain - witchcraft [complex terraforming - fiddling twists in the fabric of space]",
  "Flexi + Geiss - Tokamak mindblob 2.0",
  "Flexi + Martin - cascading decay swing",
  "Flexi + stahlregen - jelly showoff parade",
  "Flexi - alien fish pond",
  "flexi - bouncing balls [double mindblob gastrointestinal mix]",
  "flexi - bouncing balls [double mindblob neon mix]",
  "flexi - jelly fish mandala",
  "Flexi - mindblob [shiny mix]",
  "Flexi - predator-prey-spirals",
  "Flexi - predator-prey-spirals [stahlregens gelatine finish]",
  "Flexi - psychenapping",
  "flexi - swing out on the spiral",
  "Flexi, fishbrain + Martin - witchery",
  "Flexi, fishbrain, Geiss + Martin - tokamak witchery",
  "Flexi, martin + geiss - dedicated to the sherwin maxawow",
  "Flexi, martin + geiss - painterly rogue wave strike",
  "Fumbling_Foo + En D & Martin - Mandelverse",
  "Geiss - 3 layers (Tunnel Mix)",
  "Geiss - Brain Zoom 4",
  "Geiss - Cauldron - painterly (saturation remix)",
  "Geiss - Cauldron - painterly 2 (saturation remix)",
  "Geiss - Desert Rose 4",
  "Geiss - Explosion Mod 2bd (wave)",
  "Geiss - Game of Life 3",
  "Geiss - Myriad Mosaics",
  "Geiss - Planet 1",
  "Geiss - Reaction Diffusion (Puddle Mix)s a aa aa",
  "Geiss - Reaction Diffusion 2",
  "Geiss - Reaction Diffusion 3",
  "Geiss - Reaction Diffusion 3 (Lichen Mix)",
  "Geiss - Skin Dots Multi-layer 3",
  "Geiss - Tokamak Plus 2",
  "Geiss - Two-Pointed Pulsagon - mash0000 - bubonic super-fluid centrifuge",
  "Goody - Ego Decontructor",
  "GreatWho - Lasershow",
  "gunthry is out back bloodying up the pine trees - adm atomising (v) the disintigrate (n)",
  "Halfbreak - Funny Madness",
  "Halfbreak - Light of Breakers",
  "high-altitude basket unraveling - singh grooves nitrogen argon nz+",
  "Idiot - Star Of Annon",
  "Illusion & Rovastar - Dotty Mad Space (Jelly)",
  "Isosceles mashup07",
  "it is the night of the demon weed bowel",
  "Krash + Illusion - Spiral Movement",
  "LuxXx - Play v3 (the war within all of us)",
  "martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained",
  "martin + stahlregen - martin in da mash 12",
  "martin + stahlregen - martin in da mash 12a",
  "Martin - acid wiring",
  "martin - angel flight",
  "martin - another kind of groove",
  "martin - bombyx mori",
  "martin - bombyx mori [flexi′s logarithmic edit]",
  "martin - bring up the big guns",
  "martin - chain breaker",
  "Martin - charisma",
  "martin - cherry brain wall mod",
  "Martin - disco mix 6",
  "martin - elusive impressions mix2 - flacc mess proph nz+2",
  "martin - glass corridor",
  "martin - glassball dance",
  "martin - infinity (2010 update)",
  "Martin - journey into space",
  "martin - mucus cervix",
  "martin - neon space ps2 (ati fix) - yaqui graph - flx food",
  "Martin - QBikal - Surface Turbulence IIb",
  "martin - reflections on black tiles",
  "martin - The Bridge of Khazad-Dum",
  "martin - the bridge of khazad-dum [flexi's growth raised to the power of transcendence mix]",
  "martin - witchcraft reloaded",
  "martin [shadow harlequins shape code] - fata morgana",
  "Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX",
  "MilkDrop2077.R002",
  "MilkDrop2077.R012",
  "one-sided infinite-dimensional shape - helenisch",
  "ORB - Magma Pool",
  "Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix",
  "raron - a grayish blob - mash0000 - pungent gastric automata cloud fumes",
  "Rocke - Answer.42 (New Mix 1) - mash0000 - slash and char p. jungle",
  "Rovastar + Che - Asylum Animations",
  "Rovastar + Flexi - Hurricane Nightmare (Moebius Mix)",
  "Rovastar + Geiss - Hurricane Nightmare",
  "Rovastar + Geiss - Hurricane Nightmare (Relief Mix)",
  "Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)",
  "Rovastar + Loadus + Geiss - Tone-mapped FractalDrop 7c",
  "Rovastar + Telek - Altars of Madness (Rolling Oceans Mix)",
  "Rovastar - Explosive Minds",
  "Rovastar - Oozing Resistance",
  "Rovastar - Trippy Sperm (Jelly)",
  "Rovastar-altarsofmadness(forgottenrea",
  "sawtooth grin roam",
  "shifter + flexi - american oblivion pie",
  "shifter - dark tides bdrv mix",
  "shifter - dark tides bdrv mix 2",
  "shifter - escape (sigur ros)",
  "shifter - escape the worm - Eo.S. + Phat - Before_It_Eats_Your_Brain_Mix_v2",
  "shifter - feathers (angel wings)_phat_remix relief 2",
  "shifter - fire and brimstone",
  "shut down all survival paradigms",
  "Stahlregen & Boz + Eo.S + Geiss + Phat + Rovastar + Zylot - Machine Code [Jelly]",
  "stahlregen - dots (layered) - suksma world humanvirus replication killphreqs mix",
  "suksma - ed geining hateops - flx i want you, i'm sick with you",
  "suksma - feign shoulder concern when i should be executed - everything is eternally shrinking",
  "suksma - grainery clock mortis",
  "suksma - heretical crosscut playpen",
  "suksma - Hexcollie - Julian Carnival - shimmy dumb grid",
  "suksma - pus on my cat - j4+ - cubby",
  "suksma - uninitialized variabowl (hydroponic chronic)",
  "The NG + Flexi + BDRV - Ultramix, Aderrasi + Flexi - Predator Prey Spirals, Flexi - Jellyfish Jam",
  "TonyMilkdrop - Magellan's Nebula [Flexi - fancy + $this shall not retain]",
  "TonyMilkdrop - Magellan's Nebula [Flexi - you enter first + multiverse]",
  "Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix)",
  "Unchained - Making a Science of It 4",
  "Unchained - Unified Drag 2",
  "undulate harque - shit broo",
  "va ultramix - 154 [chaos]",
  "Waltra - Cosmic Wind",
  "Waltra - Ice Plasma",
  "Waltra - Square Orgy",
  "yin - 190 - Temporal fluctuations",
  "yin - 191 - Temporal singularities",
  "yin - 250 - Artificial poles of the continuum_Phat′s_Orbit_mix",
  "yin - 253 - Artificial poles of the continuum (remix #3)",
  "yin - 315 - Ocean of Light (yo im peakin yo Eo.S.-Phat)",
  "Zylot - In death there is life (Geiss Layered Mix)",
  "Zylot - Paint Spill (Music Reactive Paint Mix)",
];
