// Copyright 2023 Im-Beast. MIT license.

// GENERATED FILE — do not edit by hand.
// Regenerate with: deno run -A scripts/audit_butterchurn_catalog.ts
//
// The presets the butterchurn background cycles through, selected by rendering
// each one and keeping those that resolve to a moving image at terminal
// resolution. Of 293 presets in the catalog: 289 ok, 3 blank, 1 static.
//
// The excluded ones are not broken — most draw with custom waves, custom shapes
// and a composite shader, none of which this renderer runs, so they resolve to
// an empty screen. Every preset remains selectable by index through
// `EXOMUX_BUTTERCHURN_CATALOG`; this list only decides what auto-cycling walks.

/** Names of the presets worth cycling, in catalog order. */
export const EXOMUX_BUTTERCHURN_ROTATION: readonly string[] = [
  "$$$ Royal - Mashup (220)",
  "$$$ Royal - Mashup (273)",
  "$$$ Royal - Mashup (307)",
  "$$$ Royal - Mashup (326)",
  "$$$ Royal - Mashup (417)",
  "$$$ Royal - Mashup (431)",
  "$$$ Royal - Mashup (441)",
  "$$$ Royal - Mashup (489)",
  "269",
  "27",
  "286",
  "_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)",
  "_Eo.S. - glowsticks v2 02 - Geiss HPF",
  "_Flexi, martin + geiss - painterly rogue wave strike (color emboss mix)",
  "_Geiss - Artifact 01",
  "_Geiss - Artifact 03",
  "_Geiss - Desert Rose 2",
  "_Geiss - untitled",
  "_geiss_experimental__wavefronts",
  "_Krash + Eo.S. - Photographic Sentinel",
  "_Mig_004_version2",
  "_Mig_028",
  "_Mig_049",
  "_Mig_079",
  "_Mig_085",
  "_Mig_COLORFUL9",
  "_Mig_Oscilloscope008",
  "_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)",
  "AdamFx 2 Geiss, Zylot and Flexi - Reaction Diffusion 3 (Overload Mix 2) EATIT4 hypno",
  "AdamFX Mashup 2 Martin - reflections on black tile + Raron N Flexi ",
  "Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix",
  "Aderrasi + Geiss - Airhandler (Kali Mix) - Painterly Tendrils Colorfast",
  "Aderrasi - Airhandler (Last Breath - Calm)",
  "Aderrasi - Mother Of Pearl - mash0000 - how to piss off your eyes",
  "Aderrasi - Potion of Spirits",
  "Aderrasi - Songflower (Moss Posy)",
  "Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics",
  "Aderrasi - Veil of Steel (Steel Storm) - mash0000 - bob ross finally loses it",
  "An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B",
  "bdrv - ultramix2 #43",
  "beta106i - Burning Form (Seething Mass) - mash0000 - fire paint easter egg internals",
  "cope + flexi - colorful marble (ghost mix)",
  "cope + geiss + stahlregen - cartune (bending gelatine mix)",
  "cope + martin - mother-of-pearl",
  "Cope - Passage (mandala mix)",
  "cope - strange attractor [flexis let it grow mix] (Jelly 5.56 [volume noise zoom-in])",
  "cope - the drain to heaven",
  "Cope - The Neverending Explosion of Red Liquid Fire",
  "cope, martin + flexi - the slickery of alternative varnish",
  "DemonLD_-_Toxic_water_diffusion threx angela vs debi brown (nice)",
  "Eo.S. + flexi - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b + illumination (Stahl′s Mix)",
  "Eo.S. + Zylot - skylight (Stained Glass Majesty mix)",
  "Eo.S. - glowsticks v2 03 music",
  "Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b",
  "EoS - particle storm B - couldn't not",
  "EoS_Phat Dark_heart_nobal_cause cpe ap4+",
  "EVET + Flexi - Rainbox Splash Poolz",
  "EVET - RGB Singularity",
  "fed + flexi + geiss - tokamak repellor tech twist mix [stabilized]",
  "fed + flexi - tech test 2-1 - humpgorge",
  "fishbrain + flexi - stitchcraft",
  "fiShbRaiN + Flexi - witchcraft 2.0",
  "fiShbRaiN + geiss - witchcraft (Grow Mix 3)",
  "fiShbRaiN - toffee cream and icing sugar",
  "fiShbRaiN, flexi + martin - grafitti tagging witchcraft must be overrated - demonlord shaders - lampshade hubrys2",
  "flexi + amandio c - organic",
  "flexi + amandio c - organic [random mashup]",
  "flexi + amandio c - organic12-3d-2.milk",
  "Flexi + amandio c - piercing 05 - Kopie (2) - Kopie",
  "flexi + bdrv - acid etching (jelly v5.5)",
  "flexi + fishbrain - neon mindblob grafitti",
  "Flexi + fiShbRaiN - operation fatcap II",
  "flexi + fishbrain - witchcraft [complex terraforming - fiddling twists in the fabric of space]",
  "flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish]",
  "Flexi + Geiss - pogo-cubes on tokamak matter (Jelly 5.55)",
  "Flexi + Geiss - Tokamak mindblob 2.0",
  "Flexi + Martin - astral projection",
  "Flexi + Martin - cascading decay swing",
  "Flexi + stahlregen - jelly showoff parade",
  "flexi - alien canvas [learning]",
  "Flexi - alien fader",
  "Flexi - alien fish pond",
  "Flexi - alien web bouncer [26]",
  "Flexi - area 51",
  "flexi - bouncing balls [double mindblob gastrointestinal mix]",
  "flexi - bouncing balls [double mindblob neon mix]",
  "Flexi - crush ice 72",
  "Flexi - dimensions, projection and abstraction",
  "flexi - hyperspaceflight (bn cn Jelly 4)",
  "Flexi - infused with the spiral",
  "flexi - infused with the spiral (jelly 4.x cn)",
  "flexi - inter state",
  "flexi - jelly fish mandala",
  "flexi - Mindblob",
  "Flexi - mindblob [shiny mix]",
  "Flexi - mindblob mix",
  "flexi - mom, why the sky looks different today",
  "flexi - patternton, district of media, capitol of the united abstractions of fractopia",
  "Flexi - piercing",
  "Flexi - predator-prey-spirals",
  "Flexi - predator-prey-spirals [stahlregens gelatine finish]",
  "Flexi - psychenapping",
  "Flexi - smashing fractals 2.0",
  "Flexi - smashing fractals [acid etching mix]",
  "flexi - swing out on the spiral",
  "Flexi - truly soft piece of software - this is generic texturing (Jelly) ",
  "flexi - what is the matrix",
  "Flexi, fishbrain + Martin - witchery",
  "Flexi, fishbrain, Geiss + Martin - tokamak witchery",
  "Flexi, Geiss and Rovastar - chaos layered tokamak",
  "Flexi, martin + geiss - dedicated to the sherwin maxawow",
  "Flexi, martin + geiss - painterly rogue wave strike",
  "flexi, stahlregen, geiss + tobias wolfboi - space gelatine burst - mash0000 - chromatidal pool mirror blasphemy",
  "Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b",
  "Fumbling_Foo + En D & Martin - Mandelverse",
  "Geiss + Flexi + Martin - disconnected",
  "Geiss - 3 layers (Tunnel Mix)",
  "Geiss - Bipolar 2 Enhanced",
  "Geiss - Brain Zoom 4",
  "Geiss - Cauldron - painterly (saturation remix)",
  "Geiss - Cauldron - painterly 2 (saturation remix)",
  "Geiss - Color Pox (Acid Impression Mix) (color saturation remix)",
  "Geiss - Desert Rose 4",
  "Geiss - Explosion Mod 2bd (wave)",
  "Geiss - Game of Life 3",
  "Geiss - Myriad Mosaics",
  "Geiss - Planet 1",
  "Geiss - Reaction Diffusion (Puddle Mix)s a aa aa",
  "Geiss - Reaction Diffusion 2",
  "Geiss - Reaction Diffusion 3",
  "Geiss - Reaction Diffusion 3 (Lichen Mix)",
  "Geiss - Skin Dots Multi-layer 3",
  "Geiss - Spiral Artifact",
  "Geiss - Thumb Drum",
  "Geiss - Tokamak Plus 2",
  "Geiss - Two-Pointed Pulsagon - mash0000 - bubonic super-fluid centrifuge",
  "Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring aftermath jelly mashup]",
  "Goody + flexi - Data Crusher",
  "goody + martin - crystal palace - schizotoxin - the wild iris bloom - 16 iterations",
  "Goody - Ego Decontructor",
  "Goody - The Wild Vort",
  "GreatWho - Lasershow",
  "gunthry is out back bloodying up the pine trees - adm atomising (v) the disintigrate (n)",
  "Halfbreak - Funny Madness",
  "Halfbreak - Light of Breakers",
  "Hexcollie, Pieturp, Orb, Flexi, Geiss n Demon Lord - Premeditative Urination Clause",
  "high-altitude basket unraveling - singh grooves nitrogen argon nz+",
  "Idiot - Star Of Annon",
  "Illusion & Rovastar - Dotty Mad Space (Jelly)",
  "Isosceles mashup07",
  "it is the night of the demon weed bowel",
  "Krash + Illusion - Spiral Movement",
  "LuxXx - Play v3 (the war within all of us)",
  "martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained",
  "martin + stahlregen - martin in da mash 12",
  "martin + stahlregen - martin in da mash 12a",
  "martin + stahlregen - martin in da mash 14",
  "martin + stahlregen - martin in da mash 3",
  "Martin - acid wiring",
  "martin - angel flight",
  "martin - another kind of groove",
  "martin - baby one more time",
  "martin - bombyx mori",
  "martin - bombyx mori [flexi′s logarithmic edit]",
  "Martin - bombyx mori mix2",
  "martin - bring up the big guns",
  "martin - castle in the air",
  "martin - chain breaker",
  "Martin - charisma",
  "martin - cherry brain wall mod",
  "martin - city of shadows",
  "martin - cope - laser dome",
  "martin - crystal palace",
  "Martin - Diabolo",
  "Martin - disco mix 3 -fast",
  "martin - disco mix 4",
  "Martin - disco mix 6",
  "martin - elusive impressions mix2 - flacc mess proph nz+2",
  "martin - extreme heat",
  "martin - Flexis swarm in Martins pond [not yet a boid implementation] ",
  "martin - frosty caves 2",
  "martin - fruit machine",
  "martin - gate to moria",
  "martin - ghost city",
  "martin - glass corridor",
  "martin - glassball dance",
  "martin - ice flames",
  "martin - infinity (2010 update)",
  "martin - into the fireworks",
  "Martin - journey into space",
  "Martin - liquid arrows",
  "martin - ludicrous speed",
  "martin - mandelbox explorer - high speed demo version",
  "martin - move this body",
  "martin - mucus cervix",
  "martin - neon space ps2 (ati fix) - yaqui graph - flx food",
  "Martin - QBikal - Surface Turbulence IIb",
  "martin - reflections on black tiles",
  "martin - resonant twister - steel spring",
  "martin - rogue wave -ps3",
  "martin - satellite view",
  "martin - stormy sea (2010 update)",
  "martin - The Bridge of Khazad-Dum",
  "martin - the bridge of khazad-dum [flexi's growth raised to the power of transcendence mix]",
  "martin - tunnel race",
  "martin - witchcraft reloaded",
  "martin [shadow harlequins shape code] - fata morgana",
  "martin, fishbrain + flexi - mandelbox explorer v1 Eo.S. optimize [bipolar witchcraft mix]",
  "martin, flexi, fishbrain + sto - enterstate [random mashup]",
  "Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX",
  "MilkDrop2077.R002",
  "MilkDrop2077.R012",
  "MilkDrop2077.R033",
  "one-sided infinite-dimensional shape - helenisch",
  "ORB - Magma Pool",
  "ORB - Pastel Primer",
  "orb - toxic goo",
  "ORB - Waaa",
  "Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix",
  "PieturP - triptrap_(ultimate-trip-mix)",
  "raron - a grayish blob - mash0000 - pungent gastric automata cloud fumes",
  "rce-ordinary + flexi - far away distance (custom beat detection + bipolar colour ghost mix)",
  "Redi Jedi - i dont think those were portabello mushrooms",
  "Rocke - Answer.42 (New Mix 1) - mash0000 - slash and char p. jungle",
  "Rovastar + Che - Asylum Animations",
  "Rovastar + Flexi - Hurricane Nightmare (Moebius Mix)",
  "Rovastar + Geiss - Hurricane Nightmare",
  "Rovastar + Geiss - Hurricane Nightmare (Relief Mix)",
  "Rovastar + Geiss - Hyperkaleidoscope Glow 2 motion blur (Jelly)",
  "Rovastar + Geiss - Snapshot Of Space (LSB mix)",
  "Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)",
  "Rovastar + Loadus + Geiss - Tone-mapped FractalDrop 7c",
  "Rovastar + Telek - Altars of Madness (Rolling Oceans Mix)",
  "Rovastar - Explosive Minds",
  "Rovastar - Oozing Resistance",
  "Rovastar - Trippy Sperm (Jelly)",
  "Rovastar-altarsofmadness(forgottenrea",
  "sawtooth grin nz+ m10 w4",
  "sawtooth grin roam",
  "ShadowHarlequin - LovelyShinySquares [ liquid starburst rmx ] - unchained + rovaster - luckless - martin - starfield sector",
  "shifter + flexi - american oblivion pie",
  "shifter - dark tides bdrv mix",
  "shifter - dark tides bdrv mix 2",
  "shifter - escape (sigur ros)",
  "shifter - escape the worm - Eo.S. + Phat - Before_It_Eats_Your_Brain_Mix_v2",
  "shifter - feathers (angel wings)_phat_remix relief 2",
  "shifter - fire and brimstone",
  "shifter - liquid circuitry - conjugoth",
  "shut down all survival paradigms",
  "Stahlregen & Boz + Eo.S + Geiss + Phat + Rovastar + Zylot - Machine Code [Jelly]",
  "Stahlregen & Boz - Machine Code (Reaction Diffusion)_1 - Isosceles Tweak 08",
  "stahlregen & geiss + rovastar - fields of flowers (mashup 9 - space flower rmx) - mash0001 - pack em in, we got a long haul + flashlight",
  "Stahlregen + martin + others - Psychedelic Metal Flower",
  "stahlregen - dots (layered) - suksma world humanvirus replication killphreqs mix",
  "suksma - ed geining hateops - flx i want you, i'm sick with you",
  "suksma - ed geining hateops - squeakers",
  "suksma - feign shoulder concern when i should be executed - everything is eternally shrinking",
  "suksma - gaeomaentaec - log smell 2 - steaming wienies2",
  "suksma - grainery clock mortis",
  "suksma - heretical crosscut playpen",
  "suksma - Hexcollie - Julian Carnival - shimmy dumb grid",
  "suksma - nip tuck",
  "suksma - pus on my cat - j4+ - cubby",
  "suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression",
  "suksma - uninitialized variabowl (hydroponic chronic)",
  "suksma - vector exp 1 - couldn′t not",
  "suksma - water cooled red uranium vs dotes - freeenergynow.net",
  "The NG + Flexi + BDRV - Ultramix, Aderrasi + Flexi - Predator Prey Spirals, Flexi - Jellyfish Jam",
  "TonyMilkdrop - Leonardo Da Vinci's Balloon [Flexi - merry-go-round + techstyle]",
  "TonyMilkdrop - Magellan's Nebula [Flexi - fancy + $this shall not retain]",
  "TonyMilkdrop - Magellan's Nebula [Flexi - you enter first + multiverse]",
  "Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix)",
  "Unchained - Making a Science of It 4",
  "Unchained - Rewop",
  "Unchained - Unified Drag 2",
  "undulate harque - shit broo",
  "va ultramix - 154 [chaos]",
  "Waltra - Cosmic Wind",
  "Waltra - Ice Plasma",
  "Waltra - Square Orgy",
  "yin - 250 - Artificial poles of the continuum_Phat′s_Orbit_mix",
  "yin - 253 - Artificial poles of the continuum (remix #3)",
  "yin - 315 - Ocean of Light (yo im peakin yo Eo.S.-Phat)",
  "yin - 352 - Chromatron (warped)",
  "yin - 393 - Artificial Inspiration (music driven - outward)",
  "Zylot - In death there is life (Geiss Layered Mix)",
  "Zylot - Paint Spill (Music Reactive Paint Mix)",
  "Zylot - Star Ornament",
  "Zylot - True Visionary (Final Mix)",
];
