import * as esbuild from "npm:esbuild@0.24.2";

const outdir = "docs/assets";

if (import.meta.main) {
  await Deno.mkdir(outdir, { recursive: true });
  await Promise.all([
    buildPageBundle("examples/web/neon_exodus_page.ts", `${outdir}/neon-exodus.js`),
    buildPageBundle("examples/web/api_workbench_page.ts", `${outdir}/api-workbench.js`),
    buildPageBundle("examples/web/three_ascii_page.ts", `${outdir}/three-ascii-web.js`),
    copyThreeAsciiAssets(),
  ]);
  esbuild.stop();

  await Deno.writeTextFile("docs/index.html", pageHtml());
  await formatGeneratedHtml();
}

async function buildPageBundle(entryPoint: string, outfile: string): Promise<void> {
  await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "esm",
    target: ["es2022"],
    treeShaking: true,
    minify: false,
    sourcemap: true,
    outfile,
    banner: {
      js: "// Generated by `deno task web:pages:build`. Do not edit directly.",
    },
    plugins: [npmExternalPlugin()],
  });
}

async function copyThreeAsciiAssets(): Promise<void> {
  const assetOutdir = `${outdir}/assets`;
  await Deno.mkdir(assetOutdir, { recursive: true });
  await Promise.all([
    Deno.copyFile("src/three_ascii/assets/edgesASCII.png", `${assetOutdir}/edgesASCII.png`),
    Deno.copyFile("src/three_ascii/assets/fillASCII.png", `${assetOutdir}/fillASCII.png`),
  ]);
}

async function formatGeneratedHtml(): Promise<void> {
  const command = new Deno.Command(Deno.execPath(), {
    args: ["fmt", "docs/index.html"],
    stdout: "null",
    stderr: "inherit",
  });
  const status = await command.output();
  if (!status.success) {
    throw new Error("Failed to format generated docs/index.html.");
  }
}

function npmExternalPlugin(): esbuild.Plugin {
  return {
    name: "npm-external",
    setup(build) {
      build.onResolve({ filter: /^npm:/ }, (args) => ({
        path: args.path.replace(/^npm:/, "https://esm.sh/"),
        external: true,
      }));
    },
  };
}

function pageHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Deno TUI Web Demos</title>
    <style>
      :root {
        color-scheme: dark;
        background: #05070d;
        color: #eff7ff;
        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      }

      html,
      body {
        width: 100%;
        height: 100%;
        margin: 0;
      }

      body {
        min-height: 100vh;
        overflow-x: hidden;
        overflow-y: auto;
        background:
          radial-gradient(circle at 20% 0%, rgba(255, 66, 49, 0.18), transparent 32rem),
          radial-gradient(circle at 90% 10%, rgba(177, 124, 255, 0.16), transparent 34rem),
          #05070d;
      }

      header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1rem;
        padding: 0.75rem 1rem;
        border-bottom: 1px solid rgba(239, 247, 255, 0.16);
        background: rgba(5, 7, 13, 0.82);
      }

      h1 {
        margin: 0;
        color: #ff4231;
        font-size: clamp(1rem, 2vw, 1.35rem);
        letter-spacing: 0;
      }

      p {
        margin: 0;
        color: #5a6478;
        font-size: 0.9rem;
      }

      .demo-shell {
        display: grid;
        gap: 1rem;
        padding: 1rem;
      }

      .demo-heading {
        display: flex;
        align-items: baseline;
        justify-content: space-between;
        gap: 1rem;
        width: min(1600px, calc(100vw - 1rem));
        justify-self: center;
      }

      .demo-heading h2 {
        margin: 0;
        color: #eff7ff;
        font-size: clamp(0.95rem, 1.6vw, 1.18rem);
        letter-spacing: 0;
      }

      .demo-heading span {
        color: #5bb0ff;
        font-size: 0.82rem;
      }

      .terminal-host {
        width: min(1600px, calc(100vw - 1rem));
        height: min(760px, calc(100vh - 8rem));
        min-height: 360px;
        justify-self: center;
        outline: none;
        box-shadow: 0 0 0 1px rgba(91, 176, 255, 0.24), 0 0 48px rgba(255, 66, 49, 0.14);
        background: #05070d;
      }

      #three-ascii {
        height: min(640px, calc(100vh - 8rem));
        box-shadow: 0 0 0 1px rgba(45, 212, 191, 0.26), 0 0 48px rgba(45, 212, 191, 0.12);
      }

      #api-workbench {
        height: min(720px, calc(100vh - 8rem));
        box-shadow: 0 0 0 1px rgba(177, 124, 255, 0.24), 0 0 48px rgba(177, 124, 255, 0.12);
      }

      @media (max-width: 720px) {
        header {
          align-items: flex-start;
          flex-direction: column;
          gap: 0.25rem;
        }

        .demo-shell {
          padding: 0.5rem 0;
        }

        .demo-heading {
          align-items: flex-start;
          flex-direction: column;
          padding: 0 0.5rem;
        }

        .terminal-host {
          width: 100vw;
          height: calc(100vh - 7rem);
          min-height: 300px;
        }
      }

      canvas {
        display: block;
        width: 100%;
        height: 100%;
      }
    </style>
  </head>
  <body>
    <header>
      <h1>Neon Exodus / Deno TUI Web</h1>
      <p>Standalone client-side package demos for Neon Exodus, the API Workbench, and the three ASCII WebGPU renderer.</p>
    </header>
    <div class="demo-shell">
      <section class="demo-heading" aria-label="Neon Exodus demo description">
        <h2>Neon Exodus Browser Port</h2>
        <span>Use 1-5, O/W/E, and arrow keys.</span>
      </section>
      <main id="app" class="terminal-host" aria-label="Neon Exodus standalone browser demo"></main>
      <section class="demo-heading" aria-label="API Workbench demo description">
        <h2>API Workbench Browser Port</h2>
        <span>Click panel controls and theme labels, or use Tab, 1-4, M/F/R/T, [, ], and +/-.</span>
      </section>
      <main id="api-workbench" class="terminal-host" aria-label="API Workbench standalone browser demo"></main>
      <section class="demo-heading" aria-label="Three ASCII demo description">
        <h2>Acerola Three ASCII WebGPU Renderer</h2>
        <span>Focus the terminal and use P, G, S, Space, and arrow keys.</span>
      </section>
      <main id="three-ascii" class="terminal-host" aria-label="Three ASCII WebGPU standalone browser demo"></main>
    </div>
    <script type="module" src="./assets/neon-exodus.js"></script>
    <script type="module" src="./assets/api-workbench.js"></script>
    <script type="module" src="./assets/three-ascii-web.js"></script>
  </body>
</html>
`;
}
