import * as esbuild from "esbuild";
import { resolve } from "node:path";

const outdir = "docs/assets";
const webExternalSpecifiers = new Map([
  ["crayon", "https://deno.land/x/crayon@3.3.3/mod.ts"],
  ["jpeg-js", "https://esm.sh/jpeg-js@0.4.4"],
  ["pngjs", "https://esm.sh/pngjs@7.0.0"],
  ["three", "https://esm.sh/three@0.183.2"],
  ["three/tsl", "https://esm.sh/three@0.183.2/tsl"],
  ["three/webgpu", "https://esm.sh/three@0.183.2/webgpu"],
]);
const webExternalSpecifierPattern = /^(?:crayon|jpeg-js|pngjs|three(?:\/(?:tsl|webgpu))?)$/;
const treeShakeSafeLibraryModules = new Set([
  resolve("src/unicode/width.ts"),
]);

if (import.meta.main) {
  await Deno.mkdir(outdir, { recursive: true });
  await removeLegacyDemoAssets();
  await buildPageBundle("examples/web/api_workbench_page.ts", `${outdir}/api-workbench.js`);
  esbuild.stop();

  await Deno.writeTextFile("docs/index.html", pageHtml());
  await formatGeneratedHtml();
}

async function buildPageBundle(entryPoint: string, outfile: string): Promise<void> {
  await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "esm",
    target: ["es2022"],
    treeShaking: true,
    minify: true,
    outfile,
    banner: {
      js: "// Generated by `deno task web:pages:build`. Do not edit directly.",
    },
    plugins: [treeShakeSafeLibraryModulesPlugin(), webExternalDependencyPlugin()],
  });
}

function treeShakeSafeLibraryModulesPlugin(): esbuild.Plugin {
  return {
    name: "tree-shake-safe-library-modules",
    setup(build) {
      build.onResolve({ filter: /\.ts$/ }, (args) => {
        if (args.resolveDir.length === 0) return undefined;
        const path = resolve(args.resolveDir, args.path);
        if (!treeShakeSafeLibraryModules.has(path)) return undefined;
        return { path, sideEffects: false };
      });
    },
  };
}

async function removeLegacyDemoAssets(): Promise<void> {
  await Promise.all([
    removeIfExists(`${outdir}/api-workbench.js.map`),
    removeIfExists(`${outdir}/neon-exodus.js`),
    removeIfExists(`${outdir}/neon-exodus.js.map`),
    removeIfExists(`${outdir}/three-ascii-web.js`),
    removeIfExists(`${outdir}/three-ascii-web.js.map`),
    removeIfExists(`${outdir}/assets`),
  ]);
}

async function removeIfExists(path: string): Promise<void> {
  try {
    await Deno.remove(path, { recursive: true });
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
}

async function formatGeneratedHtml(): Promise<void> {
  const command = new Deno.Command(Deno.execPath(), {
    args: ["fmt", "docs/index.html"],
    stdout: "null",
    stderr: "inherit",
  });
  const status = await command.output();
  if (!status.success) {
    throw new Error("Failed to format generated docs/index.html.");
  }
}

function webExternalDependencyPlugin(): esbuild.Plugin {
  return {
    name: "web-external-dependency",
    setup(build) {
      build.onResolve({ filter: webExternalSpecifierPattern }, (args) => ({
        path: webExternalSpecifiers.get(args.path)!,
        external: true,
      }));
      build.onResolve({ filter: /^npm:/ }, (args) => ({
        path: npmSpecifierToEsmSh(args.path),
        external: true,
      }));
      build.onResolve({ filter: /^jsr:/ }, (args) => ({
        path: args.path,
        external: true,
      }));
    },
  };
}

function npmSpecifierToEsmSh(specifier: string): string {
  return specifier.replace(/^npm:/, "https://esm.sh/");
}

function pageHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Deno TUI Portfolio Demo</title>
    <style>
      :root {
        color-scheme: dark;
        background: #05070d;
        color: #eff7ff;
        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      }

      html,
      body {
        width: 100%;
        height: 100%;
        margin: 0;
        overscroll-behavior: none;
      }

      body {
        min-height: 100vh;
        overflow: hidden;
        display: grid;
        grid-template-rows: auto minmax(0, 1fr);
        background:
          radial-gradient(circle at 20% 0%, rgba(255, 66, 49, 0.18), transparent 32rem),
          radial-gradient(circle at 90% 10%, rgba(177, 124, 255, 0.16), transparent 34rem),
          #05070d;
      }

      header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1rem;
        padding: 0.75rem 1rem;
        border-bottom: 1px solid rgba(239, 247, 255, 0.16);
        background: rgba(5, 7, 13, 0.82);
      }

      h1 {
        margin: 0;
        color: #ff4231;
        font-size: clamp(1rem, 2vw, 1.35rem);
        letter-spacing: 0;
      }

      p {
        margin: 0;
        color: #5a6478;
        font-size: 0.9rem;
      }

      .portfolio-shell {
        display: grid;
        width: 100vw;
        height: 100%;
        min-height: 0;
      }

      .terminal-host {
        width: 100%;
        height: 100%;
        outline: none;
        touch-action: none;
        user-select: none;
        box-shadow: inset 0 0 0 1px rgba(177, 124, 255, 0.24), 0 0 48px rgba(177, 124, 255, 0.12);
        background: #05070d;
      }

      @media (max-width: 720px) {
        header {
          align-items: flex-start;
          flex-direction: column;
          gap: 0.25rem;
        }
      }

      canvas {
        display: block;
        width: 100%;
        height: 100%;
        touch-action: none;
        user-select: none;
      }
    </style>
  </head>
  <body>
    <header>
      <h1>Deno TUI Portfolio Demo</h1>
      <p>Standalone browser build of the API Workbench portfolio: windows, menus, controls, tables, themes, and canvas rendering.</p>
    </header>
    <div class="portfolio-shell">
      <main id="api-workbench" class="terminal-host" aria-label="API Workbench portfolio browser demo"></main>
    </div>
    <script type="module" src="./assets/api-workbench.js"></script>
  </body>
</html>
`;
}
