// Copyright 2023 Im-Beast. MIT license.

import {
  fingerprintUnicodeDataPackContent,
  UNICODE_DATA_PACK_SCHEMA,
  UNICODE_DATA_PACK_SCHEMA_VERSION,
  type UnicodeBinaryPropertyRanges,
  type UnicodeCodePointRange,
  type UnicodeDataPack,
  type UnicodeDataPackContent,
  type UnicodeDataPackSource,
  unicodeDataSha256,
  type UnicodeValuedRange,
  validateUnicodeDataPack,
} from "../src/unicode/data_pack.ts";

const UNICODE_VERSION = "17.0.0";
const OUTPUT_PATH = new URL("../src/unicode/generated/unicode_17_0_0.ts", import.meta.url);
const INDIC_CONJUNCT_BREAK_OUTPUT_PATH = new URL(
  "../src/unicode/generated/unicode_17_0_0_incb.ts",
  import.meta.url,
);
const GRAPHEME_RUNTIME_OUTPUT_PATH = new URL(
  "../src/unicode/generated/unicode_17_0_0_grapheme.ts",
  import.meta.url,
);
const WIDTH_RUNTIME_OUTPUT_PATH = new URL(
  "../src/unicode/generated/unicode_17_0_0_width.ts",
  import.meta.url,
);
const GRAPHEME_BREAK_TEST_OUTPUT_PATH = new URL(
  "../tests/fixtures/unicode/GraphemeBreakTest-17.0.0.txt",
  import.meta.url,
);
const MAX_SOURCE_BYTES = 2_000_000;

const SOURCES = Object.freeze(
  [
    Object.freeze({
      name: "east-asian-width",
      url: "https://www.unicode.org/Public/17.0.0/ucd/EastAsianWidth.txt",
      sha256: "ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33",
    }),
    Object.freeze({
      name: "emoji-properties",
      url: "https://www.unicode.org/Public/17.0.0/ucd/emoji/emoji-data.txt",
      sha256: "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b",
    }),
    Object.freeze({
      name: "grapheme-break",
      url: "https://www.unicode.org/Public/17.0.0/ucd/auxiliary/GraphemeBreakProperty.txt",
      sha256: "d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89",
    }),
  ] satisfies readonly UnicodeDataPackSource[],
);

const DERIVED_CORE_PROPERTIES_SOURCE: UnicodeDataPackSource = Object.freeze({
  name: "derived-core-properties",
  url: "https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt",
  sha256: "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08",
});

const DERIVED_GENERAL_CATEGORY_SOURCE: UnicodeDataPackSource = Object.freeze({
  name: "derived-general-category",
  url: "https://www.unicode.org/Public/17.0.0/ucd/extracted/DerivedGeneralCategory.txt",
  sha256: "d62e5bab70ca74f099343f71224fa051cb1fdd61a1ab45c0488c44cfc0b6102e",
});

const GRAPHEME_BREAK_TEST_SOURCE: UnicodeDataPackSource = Object.freeze({
  name: "grapheme-break-test",
  url: "https://www.unicode.org/Public/17.0.0/ucd/auxiliary/GraphemeBreakTest.txt",
  sha256: "e2d134d2c52919bace503ebb6a551c1855fe1a1faec18478c78fff254a1793ec",
});

// A pack update is deliberately incomplete until this reviewed module digest
// is changed in the same patch. `--check` never accesses the network.
const REVIEWED_MODULE_SHA256 = "52c061ca8a7fbed1a82e2b2b0c2670025e31358ea8e016e84de6500a2ff9fa62";
const REVIEWED_INDIC_CONJUNCT_BREAK_MODULE_SHA256 = "fd418400f136007a1c6e7af533d99ab01d23674d4ec439eb16e07a04884d8517";
const REVIEWED_GRAPHEME_RUNTIME_MODULE_SHA256 = "460e0ba686e75a1037c3d322e7d10f9628673397d2a32d9e06c5d5154c2f9dc4";
const REVIEWED_WIDTH_RUNTIME_MODULE_SHA256 = "53cdf3ac12e13276b644ca4e0f8932809c0875eee2eef48c8056c2fada1eaf11";

const GRAPHEME_BREAK_VALUES = Object.freeze(
  [
    "CR",
    "Control",
    "Extend",
    "L",
    "LF",
    "LV",
    "LVT",
    "Other",
    "Prepend",
    "Regional_Indicator",
    "SpacingMark",
    "T",
    "V",
    "ZWJ",
  ] as const,
);
const INDIC_CONJUNCT_BREAK_VALUES = Object.freeze(["Consonant", "Extend", "Linker"] as const);
const EAST_ASIAN_WIDTH_VALUES = Object.freeze(["A", "F", "H", "N", "Na", "W"] as const);

const MODULE_PREFIX = `// Copyright 2023 Im-Beast. MIT license.
// Generated by scripts/update_unicode_data.ts from pinned unicode.org inputs.
// Do not edit by hand; run the network-free --check mode in CI.

/** Checked-in renderer-neutral Unicode ${UNICODE_VERSION} data pack. */
export const GENERATED_UNICODE_17_0_0_DATA_PACK: unknown = JSON.parse(String.raw\``;
const MODULE_SUFFIX = "`);\n";

const INDIC_CONJUNCT_BREAK_MODULE_PREFIX = `// Copyright 2023 Im-Beast. MIT license.
// Generated by scripts/update_unicode_data.ts from a pinned unicode.org input.
// Do not edit by hand; run the network-free --check mode in CI.

/** Checked-in Unicode ${UNICODE_VERSION} Indic_Conjunct_Break data for UAX #29 GB9c. */
export const GENERATED_UNICODE_17_0_0_INDIC_CONJUNCT_BREAK_DATA: unknown = JSON.parse(String.raw\``;
const INDIC_CONJUNCT_BREAK_MODULE_SUFFIX = "`);\n";

const GRAPHEME_RUNTIME_MODULE_PREFIX = `// Copyright 2023 Im-Beast. MIT license.
// Generated by scripts/update_unicode_data.ts from the pinned Unicode data pack.
// Compact delta encoding keeps browser bundles bounded without changing UAX #29 behavior.
// Do not edit by hand; run the network-free --check mode in CI.

/** Compact checked-in Unicode ${UNICODE_VERSION} data used by the default UAX #29 segmenter. */
export const GENERATED_UNICODE_17_0_0_GRAPHEME_DATA: unknown = JSON.parse(
  String
    .raw\``;
const GRAPHEME_RUNTIME_MODULE_SUFFIX = "`,\n);\n";

const WIDTH_RUNTIME_MODULE_PREFIX = `// Copyright 2023 Im-Beast. MIT license.
// Generated by scripts/update_unicode_data.ts from pinned Unicode data.
// Compact delta encoding keeps browser bundles bounded while preserving UAX #11 tailoring.
// Do not edit by hand; run the network-free --check mode in CI.

/** Compact UAX #11 and assignment data for renderer-neutral terminal width profiles. */
// deno-fmt-ignore
export const GENERATED_UNICODE_17_0_0_WIDTH_DATA: unknown = `;
const WIDTH_RUNTIME_MODULE_SUFFIX = ";\n";

interface ParsedSourceFiles {
  readonly eastAsianWidth: string;
  readonly emoji: string;
  readonly graphemeBreak: string;
}

interface IndicConjunctBreakData {
  readonly unicodeVersion: string;
  readonly fingerprint: string;
  readonly source: UnicodeDataPackSource;
  readonly ranges: readonly UnicodeValuedRange[];
}

interface CompactGraphemeDataContent {
  readonly schema: "deno-tui.unicode-grapheme-data";
  readonly schemaVersion: 1;
  readonly unicodeVersion: string;
  readonly dataPackFingerprint: string;
  readonly indicConjunctBreakFingerprint: string;
  readonly graphemeBreakValues: readonly string[];
  readonly indicConjunctBreakValues: readonly string[];
  readonly graphemeBreakRanges: readonly number[];
  readonly extendedPictographicRanges: readonly number[];
  readonly indicConjunctBreakRanges: readonly number[];
}

interface CompactGraphemeData extends CompactGraphemeDataContent {
  readonly fingerprint: string;
}

interface CompactWidthDataContent {
  readonly schema: "deno-tui.unicode-width-data";
  readonly schemaVersion: 1;
  readonly unicodeVersion: string;
  readonly dataPackFingerprint: string;
  readonly source: UnicodeDataPackSource;
  readonly eastAsianWidthValues: readonly string[];
  readonly eastAsianWidthRanges: readonly number[];
  readonly assignedRanges: readonly number[];
  readonly combiningRanges: readonly number[];
  readonly zeroWidthRanges: readonly number[];
}

interface CompactWidthData extends CompactWidthDataContent {
  readonly fingerprint: string;
}

interface WidthCategoryRanges {
  readonly assigned: readonly UnicodeCodePointRange[];
  readonly combining: readonly UnicodeCodePointRange[];
  readonly zeroWidth: readonly UnicodeCodePointRange[];
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function parseCodePointRange(raw: string, source: string, lineNumber: number): UnicodeCodePointRange {
  const parts = raw.trim().split("..");
  if (parts.length < 1 || parts.length > 2 || parts.some((part) => !/^[0-9A-F]{4,6}$/.test(part))) {
    throw new Error(`${source}:${lineNumber}: malformed code-point range`);
  }
  const start = Number.parseInt(parts[0], 16);
  const end = Number.parseInt(parts[1] ?? parts[0], 16);
  if (start > end || end > 0x10ffff) throw new Error(`${source}:${lineNumber}: invalid code-point range`);
  return { start, end };
}

function dataLines(text: string, source: string): readonly [UnicodeCodePointRange, string][] {
  const result: [UnicodeCodePointRange, string][] = [];
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/);
  for (let index = 0; index < lines.length; index++) {
    const body = lines[index].split("#", 1)[0].trim();
    if (body.length === 0) continue;
    const fields = body.split(";");
    if (fields.length !== 2) throw new Error(`${source}:${index + 1}: expected exactly two fields`);
    const property = fields[1].trim();
    if (!/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(property)) {
      throw new Error(`${source}:${index + 1}: malformed property token`);
    }
    result.push([parseCodePointRange(fields[0], source, index + 1), property]);
  }
  return result;
}

function parseValuedRanges(text: string, source: string): readonly UnicodeValuedRange[] {
  const entries = dataLines(text, source)
    .map(([range, value]) => ({ ...range, value }))
    .sort((left, right) => left.start - right.start || left.end - right.end || compareText(left.value, right.value));
  const result: UnicodeValuedRange[] = [];
  for (const entry of entries) {
    const previous = result.at(-1);
    if (previous !== undefined && entry.start <= previous.end) {
      throw new Error(`${source}: overlapping ranges at U+${entry.start.toString(16).toUpperCase()}`);
    }
    if (previous !== undefined && previous.value === entry.value && previous.end + 1 === entry.start) {
      result[result.length - 1] = { start: previous.start, end: entry.end, value: entry.value };
    } else {
      result.push(entry);
    }
  }
  return result;
}

function parseBinaryProperties(text: string, source: string): readonly UnicodeBinaryPropertyRanges[] {
  const groups = new Map<string, UnicodeCodePointRange[]>();
  for (const [range, property] of dataLines(text, source)) {
    const ranges = groups.get(property) ?? [];
    ranges.push(range);
    groups.set(property, ranges);
  }
  return Array.from(groups.entries())
    .sort(([left], [right]) => compareText(left, right))
    .map(([property, unsortedRanges]) => {
      unsortedRanges.sort((left, right) => left.start - right.start || left.end - right.end);
      const ranges: UnicodeCodePointRange[] = [];
      for (const range of unsortedRanges) {
        const previous = ranges.at(-1);
        if (previous !== undefined && range.start <= previous.end) {
          throw new Error(`${source}/${property}: overlapping ranges at U+${range.start.toString(16).toUpperCase()}`);
        }
        if (previous !== undefined && previous.end + 1 === range.start) {
          ranges[ranges.length - 1] = { start: previous.start, end: range.end };
        } else {
          ranges.push(range);
        }
      }
      return { property, ranges };
    });
}

function mergeBinaryRanges(
  input: readonly UnicodeCodePointRange[],
  label: string,
): readonly UnicodeCodePointRange[] {
  const sorted = input.map((range) => ({ ...range })).sort((left, right) =>
    left.start - right.start || left.end - right.end
  );
  const merged: UnicodeCodePointRange[] = [];
  for (const range of sorted) {
    if (range.start < 0 || range.start > range.end || range.end > 0x10ffff) {
      throw new Error(`${label}: invalid range`);
    }
    const previous = merged.at(-1);
    if (previous !== undefined && range.start <= previous.end + 1) {
      merged[merged.length - 1] = { start: previous.start, end: Math.max(previous.end, range.end) };
    } else {
      merged.push(range);
    }
  }
  return merged;
}

function intersectBinaryRanges(
  left: readonly UnicodeCodePointRange[],
  right: readonly UnicodeCodePointRange[],
): readonly UnicodeCodePointRange[] {
  const result: UnicodeCodePointRange[] = [];
  let leftIndex = 0;
  let rightIndex = 0;
  while (leftIndex < left.length && rightIndex < right.length) {
    const leftRange = left[leftIndex];
    const rightRange = right[rightIndex];
    const start = Math.max(leftRange.start, rightRange.start);
    const end = Math.min(leftRange.end, rightRange.end);
    if (start <= end) result.push({ start, end });
    if (leftRange.end < rightRange.end) leftIndex += 1;
    else rightIndex += 1;
  }
  return result;
}

function buildWidthCategoryRanges(
  pack: UnicodeDataPack,
  generalCategoryText: string,
): WidthCategoryRanges {
  if (!generalCategoryText.replace(/^\uFEFF/, "").startsWith(`# DerivedGeneralCategory-${UNICODE_VERSION}.txt\n`)) {
    throw new Error("DerivedGeneralCategory.txt: Unicode version header is not pinned");
  }
  const generalCategories = parseValuedRanges(generalCategoryText, "DerivedGeneralCategory.txt");
  if (
    generalCategories.length === 0 || generalCategories[0].start !== 0 ||
    generalCategories.at(-1)?.end !== 0x10ffff
  ) {
    throw new Error("DerivedGeneralCategory.txt: category ranges do not cover Unicode");
  }
  for (let index = 1; index < generalCategories.length; index += 1) {
    if (generalCategories[index].start !== generalCategories[index - 1].end + 1) {
      throw new Error("DerivedGeneralCategory.txt: category ranges contain a gap");
    }
  }

  const assigned = mergeBinaryRanges(
    generalCategories.filter((range) => range.value !== "Cn"),
    "DerivedGeneralCategory assigned",
  );
  const nonspacingMarks = generalCategories.filter((range) => range.value === "Mn" || range.value === "Me");
  const hangulContinuations = pack.tables.graphemeBreak.filter((range) => range.value === "V" || range.value === "T");
  const combining = mergeBinaryRanges(
    [...nonspacingMarks, ...hangulContinuations],
    "terminal combining",
  );
  const controls = pack.tables.graphemeBreak.filter((range) =>
    range.value === "Control" || range.value === "CR" || range.value === "LF" || range.value === "ZWJ"
  );
  const extend = pack.tables.graphemeBreak.filter((range) => range.value === "Extend");
  const formats = generalCategories.filter((range) => range.value === "Cf");
  const zeroWidth = mergeBinaryRanges(
    [...controls, ...intersectBinaryRanges(extend, formats)],
    "terminal fixed zero-width",
  );

  if (
    !rangeContains(assigned, 0x0041) || !rangeContains(assigned, 0x1f600) ||
    rangeContains(assigned, 0x0378) || rangeContains(assigned, 0xfdd0) ||
    rangeContains(assigned, 0x10ffff) || rangeContains(assigned, 0x2065)
  ) {
    throw new Error("DerivedGeneralCategory.txt: assignment sentinel corpus failed");
  }
  if (
    !rangeContains(combining, 0x0301) || !rangeContains(combining, 0x1161) ||
    !rangeContains(combining, 0x11a8) || rangeContains(combining, 0x09be) ||
    rangeContains(combining, 0xff9e) || rangeContains(combining, 0x302e) ||
    rangeContains(combining, 0x1f3fb)
  ) {
    throw new Error("DerivedGeneralCategory.txt: combining sentinel corpus failed");
  }
  if (!rangeContains(zeroWidth, 0x200c) || !rangeContains(zeroWidth, 0x200d)) {
    throw new Error("DerivedGeneralCategory.txt: fixed zero-width sentinel corpus failed");
  }
  return { assigned, combining, zeroWidth };
}

function parseIndicConjunctBreakRanges(text: string): readonly UnicodeValuedRange[] {
  const entries: UnicodeValuedRange[] = [];
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/);
  for (let index = 0; index < lines.length; index++) {
    const body = lines[index].split("#", 1)[0].trim();
    if (body.length === 0) continue;
    const fields = body.split(";").map((field) => field.trim());
    if (fields.length < 2 || fields[1] !== "InCB") continue;
    if (fields.length !== 3 || !["Consonant", "Extend", "Linker"].includes(fields[2])) {
      throw new Error(`DerivedCoreProperties.txt:${index + 1}: malformed Indic_Conjunct_Break record`);
    }
    entries.push({
      ...parseCodePointRange(fields[0], "DerivedCoreProperties.txt", index + 1),
      value: fields[2],
    });
  }
  entries.sort((left, right) =>
    left.start - right.start || left.end - right.end || compareText(left.value, right.value)
  );
  const result: UnicodeValuedRange[] = [];
  for (const entry of entries) {
    const previous = result.at(-1);
    if (previous !== undefined && entry.start <= previous.end) {
      throw new Error(
        `DerivedCoreProperties.txt: overlapping Indic_Conjunct_Break ranges at U+${
          entry.start.toString(16).toUpperCase()
        }`,
      );
    }
    if (previous !== undefined && previous.value === entry.value && previous.end + 1 === entry.start) {
      result[result.length - 1] = { start: previous.start, end: entry.end, value: entry.value };
    } else {
      result.push(entry);
    }
  }
  if (!result.some((entry) => entry.value === "Consonant")) {
    throw new Error("DerivedCoreProperties.txt: Indic_Conjunct_Break Consonant data is missing");
  }
  if (!result.some((entry) => entry.value === "Linker")) {
    throw new Error("DerivedCoreProperties.txt: Indic_Conjunct_Break Linker data is missing");
  }
  return result;
}

function buildIndicConjunctBreakData(text: string): IndicConjunctBreakData {
  const content = {
    unicodeVersion: UNICODE_VERSION,
    source: DERIVED_CORE_PROPERTIES_SOURCE,
    ranges: parseIndicConjunctBreakRanges(text),
  };
  return {
    unicodeVersion: content.unicodeVersion,
    fingerprint: unicodeDataSha256(JSON.stringify(content)),
    source: content.source,
    ranges: content.ranges,
  };
}

function buildPack(files: ParsedSourceFiles): UnicodeDataPack {
  const content: UnicodeDataPackContent = {
    schema: UNICODE_DATA_PACK_SCHEMA,
    schemaVersion: UNICODE_DATA_PACK_SCHEMA_VERSION,
    unicodeVersion: UNICODE_VERSION,
    sources: SOURCES,
    tables: {
      graphemeBreak: parseValuedRanges(files.graphemeBreak, "GraphemeBreakProperty.txt"),
      eastAsianWidth: parseValuedRanges(files.eastAsianWidth, "EastAsianWidth.txt"),
      emoji: parseBinaryProperties(files.emoji, "emoji-data.txt"),
    },
  };
  return validateUnicodeDataPack({
    schema: content.schema,
    schemaVersion: content.schemaVersion,
    unicodeVersion: content.unicodeVersion,
    fingerprint: fingerprintUnicodeDataPackContent(content),
    sources: content.sources,
    tables: content.tables,
  });
}

function encodeDeltaValuedRanges(
  ranges: readonly UnicodeValuedRange[],
  values: readonly string[],
  label: string,
): number[] {
  const encoded: number[] = [];
  let previousEnd = -1;
  for (let index = 0; index < ranges.length; index++) {
    const range = ranges[index];
    const valueIndex = values.indexOf(range.value);
    if (valueIndex < 0) throw new Error(`${label} range ${index} has unsupported value ${range.value}.`);
    encoded.push(range.start - previousEnd - 1, range.end - range.start, valueIndex);
    previousEnd = range.end;
  }
  return encoded;
}

function encodeDeltaBinaryRanges(ranges: readonly UnicodeCodePointRange[]): number[] {
  const encoded: number[] = [];
  let previousEnd = -1;
  for (const range of ranges) {
    encoded.push(range.start - previousEnd - 1, range.end - range.start);
    previousEnd = range.end;
  }
  return encoded;
}

function buildCompactGraphemeData(
  pack: UnicodeDataPack,
  indicData: IndicConjunctBreakData,
): CompactGraphemeData {
  const extendedPictographic = pack.tables.emoji.find((entry) => entry.property === "Extended_Pictographic");
  if (extendedPictographic === undefined) {
    throw new Error("Unicode pack is missing the Extended_Pictographic property.");
  }
  const content: CompactGraphemeDataContent = {
    schema: "deno-tui.unicode-grapheme-data",
    schemaVersion: 1,
    unicodeVersion: pack.unicodeVersion,
    dataPackFingerprint: pack.fingerprint,
    indicConjunctBreakFingerprint: indicData.fingerprint,
    graphemeBreakValues: GRAPHEME_BREAK_VALUES,
    indicConjunctBreakValues: INDIC_CONJUNCT_BREAK_VALUES,
    graphemeBreakRanges: encodeDeltaValuedRanges(
      pack.tables.graphemeBreak,
      GRAPHEME_BREAK_VALUES,
      "Grapheme_Cluster_Break",
    ),
    extendedPictographicRanges: encodeDeltaBinaryRanges(extendedPictographic.ranges),
    indicConjunctBreakRanges: encodeDeltaValuedRanges(
      indicData.ranges,
      INDIC_CONJUNCT_BREAK_VALUES,
      "Indic_Conjunct_Break",
    ),
  };
  return { ...content, fingerprint: unicodeDataSha256(JSON.stringify(content)) };
}

function buildCompactWidthData(
  pack: UnicodeDataPack,
  categories: WidthCategoryRanges,
): CompactWidthData {
  const content: CompactWidthDataContent = {
    schema: "deno-tui.unicode-width-data",
    schemaVersion: 1,
    unicodeVersion: pack.unicodeVersion,
    dataPackFingerprint: pack.fingerprint,
    source: DERIVED_GENERAL_CATEGORY_SOURCE,
    eastAsianWidthValues: EAST_ASIAN_WIDTH_VALUES,
    eastAsianWidthRanges: encodeDeltaValuedRanges(
      pack.tables.eastAsianWidth,
      EAST_ASIAN_WIDTH_VALUES,
      "East_Asian_Width",
    ),
    assignedRanges: encodeDeltaBinaryRanges(categories.assigned),
    combiningRanges: encodeDeltaBinaryRanges(categories.combining),
    zeroWidthRanges: encodeDeltaBinaryRanges(categories.zeroWidth),
  };
  return { ...content, fingerprint: unicodeDataSha256(JSON.stringify(content)) };
}

function renderModule(pack: UnicodeDataPack): string {
  const json = JSON.stringify(pack, null, 2);
  if (json.includes("`") || json.includes("${")) throw new Error("Generated JSON is not template-literal safe.");
  return `${MODULE_PREFIX}${json}${MODULE_SUFFIX}`;
}

function renderIndicConjunctBreakModule(data: IndicConjunctBreakData): string {
  const json = JSON.stringify(data, null, 2);
  if (json.includes("`") || json.includes("${")) throw new Error("Generated JSON is not template-literal safe.");
  return `${INDIC_CONJUNCT_BREAK_MODULE_PREFIX}${json}${INDIC_CONJUNCT_BREAK_MODULE_SUFFIX}`;
}

function renderCompactGraphemeModule(data: CompactGraphemeData): string {
  const json = JSON.stringify(data);
  if (json.includes("`") || json.includes("${")) throw new Error("Generated JSON is not template-literal safe.");
  return `${GRAPHEME_RUNTIME_MODULE_PREFIX}${json}${GRAPHEME_RUNTIME_MODULE_SUFFIX}`;
}

function renderCompactWidthModule(data: CompactWidthData): string {
  const json = JSON.stringify(data);
  if (json.includes("`") || json.includes("${")) throw new Error("Generated JSON is not template-literal safe.");
  return `${WIDTH_RUNTIME_MODULE_PREFIX}${json}${WIDTH_RUNTIME_MODULE_SUFFIX}`;
}

function decodeDeltaRanges(
  raw: unknown,
  stride: 2 | 3,
  label: string,
): readonly UnicodeCodePointRange[] {
  if (!Array.isArray(raw) || raw.length === 0 || raw.length > 100_000 || raw.length % stride !== 0) {
    throw new Error(`Generated width ${label} encoding has an invalid length.`);
  }
  const ranges: UnicodeCodePointRange[] = [];
  let previousEnd = -1;
  for (let offset = 0; offset < raw.length; offset += stride) {
    const gap = raw[offset];
    const span = raw[offset + 1];
    if (!Number.isSafeInteger(gap) || !Number.isSafeInteger(span) || gap < 0 || span < 0) {
      throw new Error(`Generated width ${label} range ${offset / stride} is invalid.`);
    }
    if (stride === 3) {
      const valueIndex = raw[offset + 2];
      if (
        !Number.isSafeInteger(valueIndex) || valueIndex < 0 ||
        valueIndex >= EAST_ASIAN_WIDTH_VALUES.length
      ) {
        throw new Error(`Generated width ${label} value ${offset / stride} is invalid.`);
      }
    }
    const start = previousEnd + 1 + gap;
    const end = start + span;
    if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start < 0 || end > 0x10ffff) {
      throw new Error(`Generated width ${label} range ${offset / stride} is outside Unicode.`);
    }
    ranges.push({ start, end });
    previousEnd = end;
  }
  return ranges;
}

function rangeContains(ranges: readonly UnicodeCodePointRange[], codePoint: number): boolean {
  let low = 0;
  let high = ranges.length - 1;
  while (low <= high) {
    const middle = low + ((high - low) >>> 1);
    const range = ranges[middle];
    if (codePoint < range.start) high = middle - 1;
    else if (codePoint > range.end) low = middle + 1;
    else return true;
  }
  return false;
}

function parseCompactWidthModule(text: string): CompactWidthData {
  if (!text.startsWith(WIDTH_RUNTIME_MODULE_PREFIX) || !text.endsWith(WIDTH_RUNTIME_MODULE_SUFFIX)) {
    throw new Error("Generated compact width module wrapper is not canonical.");
  }
  const json = text.slice(WIDTH_RUNTIME_MODULE_PREFIX.length, -WIDTH_RUNTIME_MODULE_SUFFIX.length);
  let raw: unknown;
  try {
    raw = JSON.parse(json);
  } catch {
    throw new Error("Generated compact width module does not contain valid JSON data.");
  }
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("Generated compact width data is not an object.");
  }
  const value = raw as Record<string, unknown>;
  const expectedKeys = [
    "schema",
    "schemaVersion",
    "unicodeVersion",
    "dataPackFingerprint",
    "source",
    "eastAsianWidthValues",
    "eastAsianWidthRanges",
    "assignedRanges",
    "combiningRanges",
    "zeroWidthRanges",
    "fingerprint",
  ];
  if (JSON.stringify(Object.keys(value)) !== JSON.stringify(expectedKeys)) {
    throw new Error("Generated compact width data fields are not canonical.");
  }
  if (
    value.schema !== "deno-tui.unicode-width-data" || value.schemaVersion !== 1 ||
    value.unicodeVersion !== UNICODE_VERSION ||
    typeof value.dataPackFingerprint !== "string" || !/^[0-9a-f]{64}$/.test(value.dataPackFingerprint) ||
    JSON.stringify(value.source) !== JSON.stringify(DERIVED_GENERAL_CATEGORY_SOURCE) ||
    JSON.stringify(value.eastAsianWidthValues) !== JSON.stringify(EAST_ASIAN_WIDTH_VALUES)
  ) {
    throw new Error("Generated compact width metadata is not pinned.");
  }
  decodeDeltaRanges(value.eastAsianWidthRanges, 3, "East_Asian_Width");
  const assigned = decodeDeltaRanges(value.assignedRanges, 2, "assigned");
  const combining = decodeDeltaRanges(value.combiningRanges, 2, "combining");
  const zeroWidth = decodeDeltaRanges(value.zeroWidthRanges, 2, "zero-width");
  if (
    !rangeContains(assigned, 0x0041) || !rangeContains(assigned, 0x1f600) ||
    rangeContains(assigned, 0x0378) || rangeContains(assigned, 0x2fa1e) ||
    rangeContains(assigned, 0xfdd0) || rangeContains(assigned, 0x10ffff) ||
    rangeContains(assigned, 0x2065)
  ) {
    throw new Error("Generated compact width assignment ranges fail the pinned sentinel corpus.");
  }
  if (
    !rangeContains(combining, 0x0301) || !rangeContains(combining, 0x1161) ||
    !rangeContains(combining, 0x11a8) || rangeContains(combining, 0x09be) ||
    rangeContains(combining, 0xff9e) || rangeContains(combining, 0x302e) ||
    rangeContains(combining, 0x1f3fb) || !rangeContains(zeroWidth, 0x200c) ||
    !rangeContains(zeroWidth, 0x200d)
  ) {
    throw new Error("Generated compact width zero-advance ranges fail the pinned sentinel corpus.");
  }
  const content: CompactWidthDataContent = {
    schema: value.schema,
    schemaVersion: value.schemaVersion,
    unicodeVersion: value.unicodeVersion,
    dataPackFingerprint: value.dataPackFingerprint,
    source: value.source as UnicodeDataPackSource,
    eastAsianWidthValues: value.eastAsianWidthValues as readonly string[],
    eastAsianWidthRanges: value.eastAsianWidthRanges as readonly number[],
    assignedRanges: value.assignedRanges as readonly number[],
    combiningRanges: value.combiningRanges as readonly number[],
    zeroWidthRanges: value.zeroWidthRanges as readonly number[],
  };
  if (value.fingerprint !== unicodeDataSha256(JSON.stringify(content))) {
    throw new Error("Generated compact width fingerprint does not match its content.");
  }
  return { ...content, fingerprint: value.fingerprint as string };
}

function parseIndicConjunctBreakModule(text: string): IndicConjunctBreakData {
  if (
    !text.startsWith(INDIC_CONJUNCT_BREAK_MODULE_PREFIX) ||
    !text.endsWith(INDIC_CONJUNCT_BREAK_MODULE_SUFFIX)
  ) {
    throw new Error("Generated Indic_Conjunct_Break module wrapper is not canonical.");
  }
  const json = text.slice(
    INDIC_CONJUNCT_BREAK_MODULE_PREFIX.length,
    -INDIC_CONJUNCT_BREAK_MODULE_SUFFIX.length,
  );
  let raw: unknown;
  try {
    raw = JSON.parse(json);
  } catch {
    throw new Error("Generated Indic_Conjunct_Break module does not contain valid JSON data.");
  }
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("Generated Indic_Conjunct_Break data is not an object.");
  }
  const value = raw as Record<string, unknown>;
  if (value.unicodeVersion !== UNICODE_VERSION) {
    throw new Error("Generated Indic_Conjunct_Break Unicode version is not pinned.");
  }
  if (JSON.stringify(value.source) !== JSON.stringify(DERIVED_CORE_PROPERTIES_SOURCE)) {
    throw new Error("Generated Indic_Conjunct_Break source metadata is not pinned.");
  }
  if (!Array.isArray(value.ranges)) throw new Error("Generated Indic_Conjunct_Break ranges are missing.");
  const ranges = value.ranges as unknown[];
  let previousEnd = -1;
  for (let index = 0; index < ranges.length; index++) {
    const range = ranges[index];
    if (range === null || typeof range !== "object" || Array.isArray(range)) {
      throw new Error(`Generated Indic_Conjunct_Break range ${index} is invalid.`);
    }
    const entry = range as Record<string, unknown>;
    if (
      !Number.isInteger(entry.start) || !Number.isInteger(entry.end) ||
      (entry.start as number) < 0 || (entry.end as number) > 0x10ffff ||
      (entry.start as number) > (entry.end as number) || (entry.start as number) <= previousEnd ||
      !["Consonant", "Extend", "Linker"].includes(entry.value as string)
    ) {
      throw new Error(`Generated Indic_Conjunct_Break range ${index} is invalid.`);
    }
    previousEnd = entry.end as number;
  }
  const content = {
    unicodeVersion: value.unicodeVersion,
    source: value.source,
    ranges: value.ranges,
  };
  if (value.fingerprint !== unicodeDataSha256(JSON.stringify(content))) {
    throw new Error("Generated Indic_Conjunct_Break fingerprint does not match its content.");
  }
  return value as unknown as IndicConjunctBreakData;
}

function parseModule(text: string): UnicodeDataPack {
  if (!text.startsWith(MODULE_PREFIX) || !text.endsWith(MODULE_SUFFIX)) {
    throw new Error("Generated Unicode module wrapper is not canonical.");
  }
  const json = text.slice(MODULE_PREFIX.length, -MODULE_SUFFIX.length);
  let raw: unknown;
  try {
    raw = JSON.parse(json);
  } catch {
    throw new Error("Generated Unicode module does not contain valid JSON data.");
  }
  return validateUnicodeDataPack(raw);
}

function assertPinnedMetadata(pack: UnicodeDataPack): void {
  if (pack.unicodeVersion !== UNICODE_VERSION) throw new Error("Generated pack Unicode version is not pinned.");
  if (pack.sources.length !== SOURCES.length) throw new Error("Generated pack source count is not pinned.");
  for (let index = 0; index < SOURCES.length; index++) {
    const expected = SOURCES[index];
    const actual = pack.sources[index];
    if (actual.name !== expected.name || actual.url !== expected.url || actual.sha256 !== expected.sha256) {
      throw new Error(`Generated pack source metadata differs at index ${index}.`);
    }
  }
}

async function downloadSource(source: UnicodeDataPackSource): Promise<string> {
  const response = await fetch(source.url, { redirect: "error" });
  if (!response.ok) throw new Error(`Unicode source request failed (${response.status}): ${source.url}`);
  const contentLength = response.headers.get("content-length");
  if (contentLength !== null && Number(contentLength) > MAX_SOURCE_BYTES) {
    throw new Error(`Unicode source exceeds ${MAX_SOURCE_BYTES} bytes: ${source.url}`);
  }
  const bytes = new Uint8Array(await response.arrayBuffer());
  if (bytes.length > MAX_SOURCE_BYTES) {
    throw new Error(`Unicode source exceeds ${MAX_SOURCE_BYTES} bytes: ${source.url}`);
  }
  const digest = unicodeDataSha256(bytes);
  if (digest !== source.sha256) {
    throw new Error(
      `Unicode source SHA-256 mismatch for ${source.url}: expected ${source.sha256}, received ${digest}`,
    );
  }
  return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
}

async function downloadSources(): Promise<ParsedSourceFiles> {
  const textByName = new Map<string, string>();
  for (const source of SOURCES) {
    textByName.set(source.name, await downloadSource(source));
  }
  return {
    eastAsianWidth: textByName.get("east-asian-width")!,
    emoji: textByName.get("emoji-properties")!,
    graphemeBreak: textByName.get("grapheme-break")!,
  };
}

function summarize(pack: UnicodeDataPack, moduleDigest: string): string {
  const emojiRanges = pack.tables.emoji.reduce((sum, entry) => sum + entry.ranges.length, 0);
  return [
    `Unicode ${pack.unicodeVersion}`,
    `pack ${pack.fingerprint}`,
    `module ${moduleDigest}`,
    `grapheme=${pack.tables.graphemeBreak.length}`,
    `eastAsianWidth=${pack.tables.eastAsianWidth.length}`,
    `emojiProperties=${pack.tables.emoji.length}`,
    `emojiRanges=${emojiRanges}`,
  ].join(" ");
}

function packCounts(pack: UnicodeDataPack): Readonly<Record<string, number>> {
  return {
    graphemeBreakRanges: pack.tables.graphemeBreak.length,
    eastAsianWidthRanges: pack.tables.eastAsianWidth.length,
    emojiProperties: pack.tables.emoji.length,
    emojiRanges: pack.tables.emoji.reduce((sum, entry) => sum + entry.ranges.length, 0),
  };
}

function renderDiff(previous: UnicodeDataPack | undefined, next: UnicodeDataPack): string {
  const nextCounts = packCounts(next);
  if (previous === undefined) {
    return JSON.stringify(
      {
        previous: null,
        next: { unicodeVersion: next.unicodeVersion, fingerprint: next.fingerprint, counts: nextCounts },
      },
      null,
      2,
    );
  }
  const previousCounts = packCounts(previous);
  const deltas = Object.fromEntries(
    Object.keys(nextCounts).map((key) => [key, nextCounts[key] - previousCounts[key]]),
  );
  return JSON.stringify(
    {
      previous: { unicodeVersion: previous.unicodeVersion, fingerprint: previous.fingerprint, counts: previousCounts },
      next: { unicodeVersion: next.unicodeVersion, fingerprint: next.fingerprint, counts: nextCounts },
      deltas,
      sourceMetadataChanged: JSON.stringify(previous.sources) !== JSON.stringify(next.sources),
      tablesChanged: {
        graphemeBreak: JSON.stringify(previous.tables.graphemeBreak) !== JSON.stringify(next.tables.graphemeBreak),
        eastAsianWidth: JSON.stringify(previous.tables.eastAsianWidth) !== JSON.stringify(next.tables.eastAsianWidth),
        emoji: JSON.stringify(previous.tables.emoji) !== JSON.stringify(next.tables.emoji),
      },
    },
    null,
    2,
  );
}

async function check(path?: string | URL): Promise<void> {
  const target = path ?? OUTPUT_PATH;
  const text = await Deno.readTextFile(target);
  const pack = parseModule(text);
  assertPinnedMetadata(pack);
  if (renderModule(pack) !== text) throw new Error("Generated Unicode module has deterministic formatting drift.");
  const moduleDigest = unicodeDataSha256(text);
  if (moduleDigest !== REVIEWED_MODULE_SHA256) {
    throw new Error(
      `Generated Unicode module is unreviewed: expected ${REVIEWED_MODULE_SHA256}, received ${moduleDigest}`,
    );
  }
  console.log(`Unicode data check passed: ${summarize(pack, moduleDigest)}`);

  if (path === undefined) {
    const indicText = await Deno.readTextFile(INDIC_CONJUNCT_BREAK_OUTPUT_PATH);
    const indicData = parseIndicConjunctBreakModule(indicText);
    if (renderIndicConjunctBreakModule(indicData) !== indicText) {
      throw new Error("Generated Indic_Conjunct_Break module has deterministic formatting drift.");
    }
    const indicDigest = unicodeDataSha256(indicText);
    if (indicDigest !== REVIEWED_INDIC_CONJUNCT_BREAK_MODULE_SHA256) {
      throw new Error(
        `Generated Indic_Conjunct_Break module is unreviewed: expected ${REVIEWED_INDIC_CONJUNCT_BREAK_MODULE_SHA256}, received ${indicDigest}`,
      );
    }
    const graphemeBreakTest = await Deno.readFile(GRAPHEME_BREAK_TEST_OUTPUT_PATH);
    const testDigest = unicodeDataSha256(graphemeBreakTest);
    if (testDigest !== GRAPHEME_BREAK_TEST_SOURCE.sha256) {
      throw new Error(
        `GraphemeBreakTest fixture is unreviewed: expected ${GRAPHEME_BREAK_TEST_SOURCE.sha256}, received ${testDigest}`,
      );
    }
    const testText = new TextDecoder("utf-8", { fatal: true }).decode(graphemeBreakTest);
    if (!testText.startsWith(`# GraphemeBreakTest-${UNICODE_VERSION}.txt\n`)) {
      throw new Error("GraphemeBreakTest fixture version header is not pinned.");
    }
    const compactData = buildCompactGraphemeData(pack, indicData);
    const expectedCompactText = renderCompactGraphemeModule(compactData);
    const compactText = await Deno.readTextFile(GRAPHEME_RUNTIME_OUTPUT_PATH);
    if (compactText !== expectedCompactText) {
      throw new Error("Generated compact grapheme module differs from the pinned full Unicode data.");
    }
    const compactDigest = unicodeDataSha256(compactText);
    if (compactDigest !== REVIEWED_GRAPHEME_RUNTIME_MODULE_SHA256) {
      throw new Error(
        `Generated compact grapheme module is unreviewed: expected ${REVIEWED_GRAPHEME_RUNTIME_MODULE_SHA256}, ` +
          `received ${compactDigest}`,
      );
    }
    console.log(
      `Unicode grapheme data check passed: Unicode ${UNICODE_VERSION} InCB ${indicData.ranges.length} ranges, ` +
        `compact ${compactText.length} bytes ${compactDigest}, GraphemeBreakTest ${testDigest}`,
    );

    const widthText = await Deno.readTextFile(WIDTH_RUNTIME_OUTPUT_PATH);
    const widthData = parseCompactWidthModule(widthText);
    if (widthData.dataPackFingerprint !== pack.fingerprint) {
      throw new Error("Generated compact width data does not reference the pinned full Unicode pack.");
    }
    const widthCategories: WidthCategoryRanges = {
      assigned: decodeDeltaRanges(widthData.assignedRanges, 2, "assigned"),
      combining: decodeDeltaRanges(widthData.combiningRanges, 2, "combining"),
      zeroWidth: decodeDeltaRanges(widthData.zeroWidthRanges, 2, "zero-width"),
    };
    const expectedWidthData = buildCompactWidthData(pack, widthCategories);
    if (JSON.stringify(widthData) !== JSON.stringify(expectedWidthData)) {
      throw new Error("Generated compact width module differs from the pinned full Unicode data.");
    }
    if (renderCompactWidthModule(widthData) !== widthText) {
      throw new Error("Generated compact width module has deterministic formatting drift.");
    }
    const widthDigest = unicodeDataSha256(widthText);
    if (widthDigest !== REVIEWED_WIDTH_RUNTIME_MODULE_SHA256) {
      throw new Error(
        `Generated compact width module is unreviewed: expected ${REVIEWED_WIDTH_RUNTIME_MODULE_SHA256}, ` +
          `received ${widthDigest}`,
      );
    }
    console.log(
      `Unicode width data check passed: Unicode ${UNICODE_VERSION} assigned ${widthCategories.assigned.length} ranges, ` +
        `compact ${widthText.length} bytes ${widthDigest}`,
    );
  }
}

async function update(): Promise<void> {
  let previous: UnicodeDataPack | undefined;
  try {
    previous = parseModule(await Deno.readTextFile(OUTPUT_PATH));
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
  const [sourceFiles, derivedCoreProperties, derivedGeneralCategory, graphemeBreakTest] = await Promise.all([
    downloadSources(),
    downloadSource(DERIVED_CORE_PROPERTIES_SOURCE),
    downloadSource(DERIVED_GENERAL_CATEGORY_SOURCE),
    downloadSource(GRAPHEME_BREAK_TEST_SOURCE),
  ]);
  const pack = buildPack(sourceFiles);
  const indicData = buildIndicConjunctBreakData(derivedCoreProperties);
  const widthCategories = buildWidthCategoryRanges(pack, derivedGeneralCategory);
  assertPinnedMetadata(pack);
  const text = renderModule(pack);
  const compactData = buildCompactGraphemeData(pack, indicData);
  const compactText = renderCompactGraphemeModule(compactData);
  const widthData = buildCompactWidthData(pack, widthCategories);
  const widthText = renderCompactWidthModule(widthData);
  console.log(`Unicode data diff:\n${renderDiff(previous, pack)}`);
  await Deno.mkdir(new URL("../src/unicode/generated/", import.meta.url), { recursive: true });
  await Deno.writeTextFile(OUTPUT_PATH, text);
  const indicText = renderIndicConjunctBreakModule(indicData);
  await Deno.writeTextFile(INDIC_CONJUNCT_BREAK_OUTPUT_PATH, indicText);
  await Deno.writeTextFile(GRAPHEME_RUNTIME_OUTPUT_PATH, compactText);
  await Deno.writeTextFile(WIDTH_RUNTIME_OUTPUT_PATH, widthText);
  await Deno.mkdir(new URL("../tests/fixtures/unicode/", import.meta.url), { recursive: true });
  await Deno.writeTextFile(GRAPHEME_BREAK_TEST_OUTPUT_PATH, graphemeBreakTest);
  const moduleDigest = unicodeDataSha256(text);
  console.log(`Unicode data generated: ${summarize(pack, moduleDigest)}`);
  if (moduleDigest !== REVIEWED_MODULE_SHA256) {
    throw new Error(
      `Generated output is intentionally unreviewed. Inspect it, update REVIEWED_MODULE_SHA256 to ${moduleDigest}, then run --check.`,
    );
  }
  const indicDigest = unicodeDataSha256(indicText);
  console.log(
    `Unicode grapheme data generated: InCB ${indicData.ranges.length} ranges module ${indicDigest}, ` +
      `GraphemeBreakTest ${GRAPHEME_BREAK_TEST_SOURCE.sha256}`,
  );
  if (indicDigest !== REVIEWED_INDIC_CONJUNCT_BREAK_MODULE_SHA256) {
    throw new Error(
      `Generated Indic_Conjunct_Break output is intentionally unreviewed. Inspect it, update ` +
        `REVIEWED_INDIC_CONJUNCT_BREAK_MODULE_SHA256 to ${indicDigest}, then run --check.`,
    );
  }
  const compactDigest = unicodeDataSha256(compactText);
  console.log(`Unicode compact grapheme data generated: ${compactText.length} bytes module ${compactDigest}`);
  if (compactDigest !== REVIEWED_GRAPHEME_RUNTIME_MODULE_SHA256) {
    throw new Error(
      `Generated compact grapheme output is intentionally unreviewed. Inspect it, update ` +
        `REVIEWED_GRAPHEME_RUNTIME_MODULE_SHA256 to ${compactDigest}, then run --check.`,
    );
  }
  const widthDigest = unicodeDataSha256(widthText);
  console.log(
    `Unicode compact width data generated: assigned ${widthCategories.assigned.length} ranges, ` +
      `${widthText.length} bytes module ${widthDigest}`,
  );
  if (widthDigest !== REVIEWED_WIDTH_RUNTIME_MODULE_SHA256) {
    throw new Error(
      `Generated compact width output is intentionally unreviewed. Inspect it, update ` +
        `REVIEWED_WIDTH_RUNTIME_MODULE_SHA256 to ${widthDigest}, then run --check.`,
    );
  }
}

function usage(): never {
  console.error("Usage: deno run [permissions] scripts/update_unicode_data.ts --check [generated-module] | --update");
  Deno.exit(2);
}

if (import.meta.main) {
  if (Deno.args[0] === "--check" && Deno.args.length <= 2) await check(Deno.args[1]);
  else if (Deno.args[0] === "--update" && Deno.args.length === 1) await update();
  else usage();
}
